language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

install:
  # Install all required Node.js packages
  - npm install -g bower less clean-css coffee-script uglify-js
  # Install client-side libraries via Bower
  - bower install
  # Install all required Python packages
  - pip install -r requirements/development.txt

script:
  # Run all application tests
  - nosetests
  # Run all behaviour driven development tests
  - flake8

notifications:
  # Disable email notifications if something fails
  email: false
